// automatically generated by the FlatBuffers compiler, do not modify

package org.kaihua.obliop.collection.fbs;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class DoubleValue extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_22_12_06(); }
  public static DoubleValue getRootAsDoubleValue(ByteBuffer _bb) { return getRootAsDoubleValue(_bb, new DoubleValue()); }
  public static DoubleValue getRootAsDoubleValue(ByteBuffer _bb, DoubleValue obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public DoubleValue __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public double value() { int o = __offset(4); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }

  public static int createDoubleValue(FlatBufferBuilder builder,
      double value) {
    builder.startTable(1);
    DoubleValue.addValue(builder, value);
    return DoubleValue.endDoubleValue(builder);
  }

  public static void startDoubleValue(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addValue(FlatBufferBuilder builder, double value) { builder.addDouble(0, value, 0.0); }
  public static int endDoubleValue(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public DoubleValue get(int j) { return get(new DoubleValue(), j); }
    public DoubleValue get(DoubleValue obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

