// automatically generated by the FlatBuffers compiler, do not modify

package org.kaihua.obliop.collection.fbs;

@SuppressWarnings("unused")
public final class FieldUnion {
  private FieldUnion() { }
  public static final byte NONE = 0;
  public static final byte IntValue = 1;
  public static final byte DoubleValue = 2;

  public static final String[] names = { "NONE", "IntValue", "DoubleValue", };

  public static String name(int e) { return names[e]; }
}

