// automatically generated by the FlatBuffers compiler, do not modify

package org.kaihua.obliop.collection.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Vec extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_22_12_06(); }
  public static Vec getRootAsVec(ByteBuffer _bb) { return getRootAsVec(_bb, new Vec()); }
  public static Vec getRootAsVec(ByteBuffer _bb, Vec obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Vec __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public org.kaihua.obliop.collection.fbs.Row rows(int j) { return rows(new org.kaihua.obliop.collection.fbs.Row(), j); }
  public org.kaihua.obliop.collection.fbs.Row rows(org.kaihua.obliop.collection.fbs.Row obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int rowsLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public org.kaihua.obliop.collection.fbs.Row.Vector rowsVector() { return rowsVector(new org.kaihua.obliop.collection.fbs.Row.Vector()); }
  public org.kaihua.obliop.collection.fbs.Row.Vector rowsVector(org.kaihua.obliop.collection.fbs.Row.Vector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createVec(FlatBufferBuilder builder,
      int rowsOffset) {
    builder.startTable(1);
    Vec.addRows(builder, rowsOffset);
    return Vec.endVec(builder);
  }

  public static void startVec(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addRows(FlatBufferBuilder builder, int rowsOffset) { builder.addOffset(0, rowsOffset, 0); }
  public static int createRowsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startRowsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endVec(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Vec get(int j) { return get(new Vec(), j); }
    public Vec get(Vec obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

