/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class org_kaihua_obliop_interfaces_cjni_CJniUtil */

#ifndef _Included_org_kaihua_obliop_interfaces_cjni_CJniUtil
#define _Included_org_kaihua_obliop_interfaces_cjni_CJniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_kaihua_obliop_interfaces_cjni_CJniUtil
 * Method:    doGetAddrFromByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;)J
 */
JNIEXPORT jlong JNICALL Java_org_kaihua_obliop_interfaces_cjni_CJniUtil_doGetAddrFromByteBuffer
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
