/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_kaihua_obliop_interfaces_ObliJni */

#ifndef _Included_org_kaihua_obliop_interfaces_ObliJni
#define _Included_org_kaihua_obliop_interfaces_ObliJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_kaihua_obliop_interfaces_ObliJni
 * Method:    hello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_kaihua_obliop_interfaces_ObliJni_hello
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_kaihua_obliop_interfaces_ObliJni
 * Method:    doObliDataGet
 * Signature: (Ljava/lang/String;Lorg/kaihua/obliop/data/JniDataReciver;)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_kaihua_obliop_interfaces_ObliJni_doObliDataGet
  (JNIEnv *, jclass, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
